refactor: organize interfaces into models directory and improve test robustness
cognovi-ai/the-cdj pull request #167
Opened 2024-09-23 20:58 UTC by hiyaryan

This PR addresses the reviews left by @davidzlu in PR #163. The following updates have been made:

- Refactored Assistants
  - Moved interfaces (`Permission`, `Model`, `ModelsResponse`, `Entry`, `EntryAnalysis`, `Message`, `ChatMessage`, `Prompt`, `ChatCompletionChoice`, `ChatCompletionUsage`, `ChatCompletionResponse`) into a new `interfaces` directory.
  - Updated import statements across modules to reference the new interface files.
  - Created separate files for each interface to promote reusability and maintainability.

- Improved Assistants test `should return the filtered model when it exists`
  - Updated test to avoid reliance on array indices in tests.
  - Modified the test to search for the expected model based on properties, making it more robust against changes in the models array.

2024-09-24 01:10 UTC, davidzlu requested changes
This is an interesting setup for the interfaces, but I think I'd prefer putting them closer to where they'd be used rather than separating them into an interfaces directory. I think my main question is what are all the interfaces representing in the application? It wasn't clear to me from the code alone, because some types seemed to be used once and never popped up again, e.g. Permission.

I think the change to the unit test is good, but I'd go back to what you have in the original PR for everything else. Sorry for the confusion

2024-09-24 03:45 UTC, hiyaryan commented on backend/src/interfaces/assistants/Model.ts
Thank you for the review @davidzlu! No need to apologize. I actually agree—I find it more practical when they're in their original files because they're only being used there. 

Here's the reasons these interfaces were made:

- Type Safety: Ensures that all data structures are well-defined, preventing runtime errors due to incorrect data handling.
- Code Clarity: Makes the code more readable and maintainable by explicitly stating what each function expects and returns.
- Avoiding `any`: Complies with the `@typescript-eslint/no-explicit-any` rule, promoting best practices in TypeScript development.
- API Compliance: Matches the data structures returned by the OpenAI API, ensuring that the application can interact with the API correctly.
- Enhanced Developer Experience: Provides better IntelliSense support in IDEs, making development more efficient and reducing the likelihood of bugs.

Does this help clear up anything or do you still have reservations? I'm totally open to hear if you do. Otherwise, if you have any questions on any of the interfaces, I'll be writing up some informal documentation and will share it with you. 

Speaking of documentation, we'll have to work on that soon. I'll add it as an action item to our BE Plan of Action doc.

2024-09-24 20:00 UTC, hiyaryan commented
Closing pull request. Kept unit test and committed it directly to PR #163. Discarded interfaces directory.

2024-09-24 20:00 UTC, closed without merging

2024-09-25 00:15 UTC, davidzlu commented on backend/src/interfaces/assistants/Model.ts
Sure that all makes sense. Thanks for the clarification!