refactor!: migrate access middleware to TS with unit tests
cognovi-ai/the-cdj pull request #185
Opened 2024-10-31 01:49 UTC by hiyaryan

This PR migrates `access` middleware to TS with unit test. It adds
- `"@types/jsonwebtoken"` to package.json.
- 100% unit test coverage.
-  Opens a new [issue](https://github.com/cognovi-ai/the-cdj/issues/184) to update `ExpressError` to provide error server side logging.
- Conditional to `isLoggedIn` `authHeader` variable to check for `authorization` property before assigning it (middleware/access.ts Line: 33)

2024-10-31 20:07 UTC, davidzlu requested changes
Nice job overall with this! There's a couple of env variables that don't seem to be getting reset in the tests, but after fixing that I think it's ready to be merged! Let me know if you want me to take care of that, or if it was intentional.

2024-10-31 20:07 UTC, davidzlu commented on package.json
> +    "@types/jsonwebtoken": "^9.0.7",
Did you mean to install this in the root package.json file or did you mean to install it into backend/package.json?

2024-11-01 00:44 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +// Middleware.ts
Oop, yes that's an llm thing. Weird how it adds comments like this sometimes. I'll remove it.

2024-11-01 00:47 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +declare module 'express-serve-static-core' {
We're actually doing something like this on the frontend for types. So we can refer to it as an example if needed. But yeah, I think it's a later thing. I'll make an issue for it.

2024-11-01 00:50 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +  // TODO: Add server-side logging for errors; Expand ExpressError to include a
Sounds like a good idea. I already created an issue for this TODO. So yeah, backlogged for now, but I think it should be one of the first things we do once the migration is complete.

2024-11-01 00:55 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +        new ExpressError('You must be logged in to access this page.', 401)
This is a good idea! Maybe when we implement the error logging we can work this in. We can have those specific errors inherit from `ExpressError` or create our own `AppError` that they can all extend from. I'll make an issue!

2024-11-08 18:46 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +declare module 'express-serve-static-core' {
#188

2024-11-08 18:52 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +  if (req.isAuthenticated && req.isAuthenticated()) {
That is weird. Definitely should just be `req.isAuthenticated()`. LLM is disappointing me, get gud.

2024-11-08 18:55 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +        new ExpressError('You must be logged in to access this page.', 401)
#184

2024-11-08 18:57 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +  // TODO: Add server-side logging for errors; Expand ExpressError to include a
#184

2024-11-08 19:07 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +  if (req.isAuthenticated && req.isAuthenticated()) {
This unit test, `should call next with error if req.isAuthenticated is undefined`, will be deleted after removing `req.isAuthenticated`

2024-11-08 19:14 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +      (jwt.verify as jest.Mock).mockImplementation((token, secret, callback) => {
I think it's alright. Don't want to get hung up on unit tests. Provided they make sense/are useful, they're doing what we want them to do and at a reasonable speed, I think that's enough. Also, `any`'s are OK to use in unit tests (I'm not sure if we discussed that yet).

2024-11-08 19:15 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +      (jwt.verify as jest.Mock).mockImplementation((token, secret, callback) => {
@davidzlu

2024-11-11 21:52 UTC, hiyaryan commented on backend/src/middleware/access.ts
> +export const requestBetaAccess = async (
Discussed that this wouldn't be refactored since the function is set to become obsolete in the near future.

2024-11-11 21:56 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +      process.env.JWT_SECRET = 'testsecret';
Resolved. Environment variables are now being restored in `afterAll`.

2024-11-11 21:56 UTC, hiyaryan commented on backend/tests/middleware/access.test.ts
> +      process.env.RELEASE_PHASE = 'beta';
Resolved. Environment variables are now being restored in `afterAll`.

2024-11-11 21:57 UTC, merged